### ISSUE TITLE
The Change you wanted was rejected

### ISSUE THREAD

**Issue by rcampany** [brotherclone/peter-koper#56] opened 2022-03-11 18:25 UTC
I was browsing the front end, and this very elegant error message showed up

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/10439748/157928274-a18c5e7f-219a-4993-8303-5b8f49ba01e8.png">

**Comment by brotherclone** [comment] 2022-03-11 19:02
Be the rejected change you wanna be, man.

**Comment by brotherclone** [comment] 2022-03-11 19:04
This may be a duplicate of or related to #47

**Comment by brotherclone** [comment] 2022-03-12 19:05
This navigation will not be in the new version.

**Closed by brotherclone** 2022-03-12 19:05 UTC
Labels: bug
